name: Atualizacao Diaria Aiven

on:
  schedule:
    - cron: '0 9 * * *' # Roda todo dia as 09:00 UTC
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código (Checkout)
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install pandas sqlalchemy pymysql requests cryptography

      - name: Rodar Script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python script.py
