name: Keep Alive (Ping de Hora em Hora)

on:
  schedule:
    # Cron: Minuto 0, a cada 1 hora ('*/1')
    - cron: '0 */1 * * *'
  workflow_dispatch: # Botão para testar manualmente se quiser

jobs:
  ping-job:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências leves
        # Só precisamos do básico para conectar
        run: |
          pip install sqlalchemy pymysql

      - name: Rodar Ping
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python ping.py
